"""File Data Model

Revision ID: 0391d1930871
Revises: cc8731159dda
Create Date: 2022-01-19 18:04:41.520193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0391d1930871"
down_revision = "cc8731159dda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_file_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("uid", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["project_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_file_pages_number"),
        "project_file_pages",
        ["number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_file_pages_uid"), "project_file_pages", ["uid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_file_pages_uid"), table_name="project_file_pages")
    op.drop_index(op.f("ix_project_file_pages_number"), table_name="project_file_pages")
    op.drop_table("project_file_pages")
    # ### end Alembic commands ###
