"""Project Printing Agency

Revision ID: 06de47a09e0b
Revises: b5750395f33a
Create Date: 2022-03-01 18:32:14.840187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06de47a09e0b"
down_revision = "b5750395f33a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_printing_agency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("works", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("uid", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_printing_agency_uid"),
        "project_printing_agency",
        ["uid"],
        unique=True,
    )
    op.add_column(
        "project_orders", sa.Column("printing_agency_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "project_orders",
        "project_printing_agency",
        ["printing_agency_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project_orders", type_="foreignkey")
    op.drop_column("project_orders", "printing_agency_id")
    op.drop_index(
        op.f("ix_project_printing_agency_uid"), table_name="project_printing_agency"
    )
    op.drop_table("project_printing_agency")
    # ### end Alembic commands ###
