"""user id on file version

Revision ID: 566f0a520019
Revises: 7f3fe8e87661
Create Date: 2022-03-16 14:30:33.585606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "566f0a520019"
down_revision = "7f3fe8e87661"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_file_versions", sa.Column("user_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "project_file_versions", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project_file_versions", type_="foreignkey")
    op.drop_column("project_file_versions", "user_id")
    # ### end Alembic commands ###
