"""Add name to project group

Revision ID: 6d95b39d94a7
Revises: 53bd86ad7c60
Create Date: 2021-09-22 01:07:30.582801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d95b39d94a7"
down_revision = "53bd86ad7c60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_gourps", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_gourps", "name")
    # ### end Alembic commands ###
