"""PROJECT ORDER

Revision ID: 6ebd1b9737e8
Revises: 0391d1930871
Create Date: 2022-01-31 12:39:03.196660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6ebd1b9737e8"
down_revision = "0391d1930871"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("uid", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_orders_uid"), "project_orders", ["uid"], unique=True
    )
    op.create_table(
        "file_order_associations",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("uid", sa.String(), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["project_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["project_orders.id"],
        ),
        sa.PrimaryKeyConstraint("file_id", "order_id"),
    )
    op.create_index(
        op.f("ix_file_order_associations_uid"),
        "file_order_associations",
        ["uid"],
        unique=True,
    )
    op.drop_constraint(
        "project_file_pages_user_id_fkey", "project_file_pages", type_="foreignkey"
    )
    op.drop_column("project_file_pages", "user_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_file_pages",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "project_file_pages_user_id_fkey",
        "project_file_pages",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_file_order_associations_uid"), table_name="file_order_associations"
    )
    op.drop_table("file_order_associations")
    op.drop_index(op.f("ix_project_orders_uid"), table_name="project_orders")
    op.drop_table("project_orders")
    # ### end Alembic commands ###
