"""file versions

Revision ID: 7f3fe8e87661
Revises: 06de47a09e0b
Create Date: 2022-03-16 10:25:00.003297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7f3fe8e87661"
down_revision = "06de47a09e0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_file_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_version_id", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("uid", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["project_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_file_versions_external_version_id"),
        "project_file_versions",
        ["external_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_file_versions_uid"),
        "project_file_versions",
        ["uid"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_file_versions_uid"), table_name="project_file_versions"
    )
    op.drop_index(
        op.f("ix_project_file_versions_external_version_id"),
        table_name="project_file_versions",
    )
    op.drop_table("project_file_versions")
    # ### end Alembic commands ###
