"""resources and permissions

Revision ID: 9586952a8cc6
Revises: 453afd751b15
Create Date: 2021-12-01 13:28:45.174839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9586952a8cc6"
down_revision = "453afd751b15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("uid", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("object_uid", sa.String(), nullable=True),
        sa.Column("object_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_permissions_object_uid"), "permissions", ["object_uid"], unique=False
    )
    op.create_index(op.f("ix_permissions_uid"), "permissions", ["uid"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_permissions_uid"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_object_uid"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
