"""Files Users Relationship

Revision ID: 9b3319418994
Revises: 36c5534e53f9
Create Date: 2021-11-21 14:27:32.911659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9b3319418994"
down_revision = "36c5534e53f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_files", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "project_files", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project_files", type_="foreignkey")
    op.drop_column("project_files", "user_id")
    # ### end Alembic commands ###
