"""paying user

Revision ID: 9d8c1b4e137f
Revises: 9586952a8cc6
Create Date: 2021-12-06 18:43:03.043080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9d8c1b4e137f"
down_revision = "9586952a8cc6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("paying", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "paying")
    # ### end Alembic commands ###
