"""Subscribe Project

Revision ID: ab59291ce38b
Revises: 0c3073574ea1
Create Date: 2022-02-23 20:25:34.872205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab59291ce38b"
down_revision = "0c3073574ea1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("integrations", sa.Column("uid", sa.String(), nullable=True))
    op.add_column("integrations", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_integrations_uid"), "integrations", ["uid"], unique=True)
    op.add_column(
        "user_project_associations", sa.Column("subscribe", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_project_associations", "subscribe")
    op.drop_index(op.f("ix_integrations_uid"), table_name="integrations")
    op.drop_column("integrations", "created_at")
    op.drop_column("integrations", "uid")
    # ### end Alembic commands ###
