"""File Description

Revision ID: b5750395f33a
Revises: ab59291ce38b
Create Date: 2022-02-28 23:47:46.632959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b5750395f33a"
down_revision = "ab59291ce38b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_files", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_files", "description")
    # ### end Alembic commands ###
