"""mail messages stacker

Revision ID: c2b9e08a1c19
Revises: 6ebd1b9737e8
Create Date: 2022-02-11 11:38:57.025715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c2b9e08a1c19"
down_revision = "c3b5d57649d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("sender_id", sa.Integer(), nullable=True),
        sa.Column("recipient_id", sa.Integer(), nullable=True),
        sa.Column("external_message_id", sa.String(), nullable=True),
        sa.Column("delivered", sa.Boolean(), nullable=True),
        sa.Column("delivery_time", sa.DateTime(), nullable=True),
        sa.Column("opened", sa.Boolean(), nullable=True),
        sa.Column("opening_time", sa.DateTime(), nullable=True),
        sa.Column("uid", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mails_uid"), "mails", ["uid"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_orders",
        sa.Column("supplier_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "project_orders_supplier_id_fkey",
        "project_orders",
        "users",
        ["supplier_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_mails_uid"), table_name="mails")
    op.drop_table("mails")
    # ### end Alembic commands ###
