"""Project status record.

Revision ID: c2f0bc2228a2
Revises: 6d95b39d94a7
Create Date: 2021-09-22 23:19:49.761853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2f0bc2228a2"
down_revision = "6d95b39d94a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_group_roles", sa.Column("deadline", sa.DateTime(), nullable=True)
    )
    op.add_column("projects", sa.Column("status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "status")
    op.drop_column("project_group_roles", "deadline")
    # ### end Alembic commands ###
